[package]
name = "cliverge"
version = "0.1.0"
edition = "2021"
description = "GUI interface for CLIverge"

# Hide console window on Windows
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "consoleapi"] }

[dependencies]
cliverge-core = { path = "../cliverge-core" }
eframe = "0.24"
egui = "0.24"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
dirs = { workspace = true }
chrono = { workspace = true }
webbrowser = "0.8"
image = "0.24"

# Windows resource file for icon
[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "cliverge"
path = "src/main.rs"

